import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={`${styles.main} ${inter.className}`}>
        
        <div className={styles.mainimg}>
          <img className={styles.myimg} src="/HomeImg.jpg" alt="Hunting coder" width="200" height="140" />
        </div>
        <div className={styles.center} >
          <h2>&lt;Hunting coder/&gt;</h2>
        </div>
          <div className={styles.blogcon}>
            <h2 className={styles.blogHeadline}>Latest blogs</h2>
            <div className="blogitems">
              <h3 className={styles.h3}>how to learn javascript in 2022?</h3>
              <p className={styles.p} >javascript is a language used to design logic in websites. Lorem ipsum dolor sit amet consectetur adipisicing elit.</p >
              <button className={styles.btn}>Read more</button>
            </div>
            <div className="blogitems">
              <h3 className={styles.h3}>how to learn javascript in 2022?</h3>
              <p className={styles.p} >javascript is a language used to design logic in websites</p >
              <button className={styles.btn}>Read more</button>
            </div>
            <div className="blogitems">
              <h3 className={styles.h3}>how to learn javascript in 2022?</h3>
              <p className={styles.p} >javascript is a language used to design logic in websites</p >
              <button className={styles.btn}>Read more</button>
            </div>
          </div> 
      </main>
    </>
  )
}
